---
name: cleanvid-build-push-ghcr
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cleanvid
  IMAGE_TAG: latest
  IMAGE_ARCH: amd64
  REPO_CONTEXT: .
  REPO_CONTAINERFILE: ./docker/Dockerfile
concurrency:
  group: cleanvid-${{ github.ref }}
  cancel-in-progress: true
jobs:
  buildah:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      security-events: write
    steps:
      - name: Checkout
        id: repo-checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2
      - name: Log in to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: ${{ env.REPO_CONTAINERFILE }}
          archs: ${{ env.IMAGE_ARCH }}
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          scan-type: 'image'
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          hide-progress: true
          ignore-unfixed: true
          exit-code: '0'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Push
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
